name: ci

on:
  schedule:
    - cron: '0 22 * * *'
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          pull: true
          tags: raykrueger/satisfactory-dedicated-server:latest
      - name: Build and Push Experimental
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: STEAMARGS=-beta experimental
          push: true
          pull: true
          tags: raykrueger/satisfactory-dedicated-server:experimental
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: raykrueger/satisfactory-dedicated-server
